### ISSUE TITLE
Add a translation framework to the site

### ISSUE THREAD

**Issue by gabmontes** [purefinance/pure.finance#16]
Add `next-translate` as translation framework.

**Comment by mbonfoster** [comment]
After dedicating some hours to this issue, we will need to decide what approach we should take since at least now i18n support is not compatible with next export which we are using to export the Next.js application as static.
See:
https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation
https://github.com/vercel/next.js/discussions/18957
https://github.com/vercel/next.js/issues/18318
I've also tried some workarounds like https://github.com/vercel/next.js/issues/18318#issuecomment-724071925 but didn't work either.

**Comment by adrai** [comment]
This may help? https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd
